### ISSUE TITLE
var greeting = "Very good job Hanna!"

### ISSUE THREAD

**Issue by odi89** [HThNoordzij/Vennegruppe_python#1]
Just ran trough your Python code, and i looks super neat. You really made tool of value for frustrated parents=) Love to hear the response from the school

Good job!

-Sebastian

**Comment by HThNoordzij** [comment]
Thanks for trying Sebastian! Good to hear it worked :-)

I'm afraid I'll need to build a simple GUI around the app so the parents can use it on their own. But until then I can be be the vennegruppe service.
